# Generated by Django 5.0.3 on 2024-04-16 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('pdf', models.FileField(upload_to='../../core/static')),
                ('resourceId', models.TextField(max_length=50)),
                ('uploadDate', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='query',
            name='answer',
            field=models.TextField(default='you forgot to enter a query'),
        ),
        migrations.AlterField(
            model_name='query',
            name='question',
            field=models.TextField(default='you forgot to enter a query'),
        ),
        migrations.AddField(
            model_name='query',
            name='Conversation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='queries.conversation'),
        ),
    ]
