# Generated by Django 5.0.3 on 2024-04-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_conversation_alter_query_answer_alter_query_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.TextField(default='empty', max_length=50),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='pdf',
            field=models.FileField(default='empty', upload_to='../../core/static'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='resourceId',
            field=models.TextField(default='empty', max_length=50),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='uploadDate',
            field=models.DateTimeField(default='empty'),
        ),
        migrations.AlterField(
            model_name='query',
            name='Conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.conversation'),
        ),
        migrations.AlterField(
            model_name='query',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='question',
            field=models.TextField(),
        ),
    ]
