# Generated by Django 5.0.3 on 2024-04-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_alter_conversation_name_alter_conversation_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='uploadDate',
            field=models.DateTimeField(),
        ),
    ]
