# Generated by Django 5.0.3 on 2024-04-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_alter_conversation_uploaddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='Conversation',
            new_name='conversation_id',
        ),
    ]
