# Generated by Django 5.0.3 on 2024-04-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0006_rename_conversation_query_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='resourceId',
            field=models.TextField(max_length=50),
        ),
    ]
