# Generated by Django 5.0.3 on 2024-04-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0011_alter_conversation_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='pdf',
            field=models.FileField(upload_to='static'),
        ),
    ]
