# Generated by Django 5.0.3 on 2024-04-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0014_alter_conversation_resourceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='resourceId',
            field=models.TextField(blank=True, max_length=25),
        ),
    ]
