# Generated by Django 5.0.3 on 2024-04-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0015_alter_conversation_resourceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='resourceId',
            new_name='sourceId',
        ),
    ]
