# Generated by Django 5.0.3 on 2024-04-18 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0016_rename_resourceid_conversation_sourceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='conversation_id',
            new_name='conversation',
        ),
    ]
